### ISSUE TITLE
Steps to Visualize Litmus Metrics and Generate Notifications

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/tutorials#6]

**Comment by ksatchit** [comment]
## Monitoring Infra Setup 

- Install the kube-prometheus-stack via its helm chart 

```bash
kubectl create ns monitoring
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
helm install prom prometheus-community/kube-prometheus-stack --namespace monitoring
```

- Verify that the prometheus operator, prometheus statefulset cluster instance, alertmanager statefulset cluster instance and grafana deployment are installed and running (you will see node-exporter daemonset & the kube-state-metrics deployment as well)

```bash
kubectl get pods -n monitoring 

NAME                                                     READY   STATUS    RESTARTS   AGE
alertmanager-prom-kube-prometheus-stack-alertmanager-0   2/2     Running   0          7h55m
prom-grafana-866b8d5685-6nrbc                            2/2     Running   0          29h
prom-kube-prometheus-stack-operator-c6f4dcdb9-9sv5w      1/1     Running   0          29h
prom-kube-state-metrics-5f44797794-jtv9m                 1/1     Running   0          29h
prom-prometheus-node-exporter-fbfx4                      1/1     Running   0          29h
prom-prometheus-node-exporter-m8f22                      1/1     Running   0          29h
prom-prometheus-node-exporter-mw4f2                      1/1     Running   0          29h
prometheus-prom-kube-prometheus-stack-prometheus-0       2/2     Running   1          9h
```

**Comment by ksatchit** [comment]
## Monitoring Infra Setup 

- Install the kube-prometheus-stack via its helm chart 

```bash
kubectl create ns monitoring
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
helm install prom prometheus-community/kube-prometheus-stack --namespace monitoring
```

- Verify that the prometheus operator, prometheus statefulset cluster instance, alertmanager statefulset cluster instance and grafana deployment are installed and running (you will see node-exporter daemonset & the kube-state-metrics deployment as well)

```bash
kubectl get pods -n monitoring 

NAME                                                     READY   STATUS    RESTARTS   AGE
alertmanager-prom-kube-prometheus-stack-alertmanager-0   2/2     Running   0          7h55m
prom-grafana-866b8d5685-6nrbc                            2/2     Running   0          29h
prom-kube-prometheus-stack-operator-c6f4dcdb9-9sv5w      1/1     Running   0          29h
prom-kube-state-metrics-5f44797794-jtv9m                 1/1     Running   0          29h
prom-prometheus-node-exporter-fbfx4                      1/1     Running   0          29h
prom-prometheus-node-exporter-m8f22                      1/1     Running   0          29h
prom-prometheus-node-exporter-mw4f2                      1/1     Running   0          29h
prometheus-prom-kube-prometheus-stack-prometheus-0       2/2     Running   1          9h

**Comment by ksatchit** [comment]
## Chaos-Interleaved Grafana Dashboards

- Login to the grafana dashboard (prom-operator/admin are the likely credentials. Edit the secret `prom-grafana` to replace with desired username/password)

- Add the prometheus data source in Grafana (there might be a pre-existing entry for the shown ds):

![image](https://user-images.githubusercontent.com/21166217/121630238-67317180-ca9a-11eb-9495-d4e87ab8e981.png)

 - Create a sample dashboard

**Comment by ksatchit** [comment]
## Chaos-Interleaved Grafana Dashboards

- Login to the grafana dashboard (prom-operator/admin are the likely credentials. Edit the secret `prom-grafana` to replace with desired username/password)

- Add the prometheus data source in Grafana (there might be a pre-existing entry for the shown ds):

![image](https://user-images.githubusercontent.com/21166217/121630238-67317180-ca9a-11eb-9495-d4e87ab8e981.png)

 - Create a sample dashboard

**Comment by ksatchit** [comment]
## Trigger a Chaos Experiment 

- Now let us trigger a chaos experiment, say, `pod-delete` against the podtatohead helloservice to view impact of chaos on the grafana dashboard. We will also add some steady-state hypothesis constraints around the availability & access characteristics of this service in the experiment run using Litmus Probes. The idea is to deliberately cause a failure of the experiment and visualize the slack alert/notification based on the rule we have created earlier in this exercise. 

- To do this (a) Install the pod-delete chaosexperiment CR in the litmus namespace (b) Prepare a ChaosEngine with the probe specifications. 

```bash
kubectl apply -f https://hub.litmuschaos.io/api/chaos/1.13.5?file=charts/generic/pod-delete/experiment.yaml -n litmus 
```

```yaml
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: hello-chaos
  namespace: litmus
spec:
  appinfo:
    appns: 'demospace'
    applabel: 'app=helloservice'
    appkind: 'deployment'
  annotationCheck: 'false'
  engineState: 'active'
  chaosServiceAccount: litmus-admin
  monitoring: false
  jobCleanUpPolicy: 'retain'
  experiments:
    - name: pod-delete
      spec:
        probe:
          - name: http-probe
            type: "httpProbe"
            httpProbe/inputs:
              url: "http://104.154.133.35:31798"
              insecureSkipVerify: false
              method:
                get:
                  criteria: "=="
                  responseCode: "200"
            mode: "Continuous"
            runProperties:
              probeTimeout: 1
              interval: 1
              retry: 1
              probePollingInterval: 1
        components:
          env:
            # set chaos duration (in sec) as desired
            - name: TOTAL_CHAOS_DURATION
              value: '10'

            # set chaos interval (in sec) as desired
            - name: CHAOS_INTERVAL
              value: '10'

            # pod failures without '--force' & default terminationGracePeriodSeconds
            - name: FORCE
              value: 'false'
```
